PDP features
vtex-apps/app-store-theme pull request #130
Opened 2020-11-16 13:58 UTC by manoel-gumes

#### What problem is this solving?

#### How should this be manually tested?

[Workspace](url)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] Refactoring

2020-11-16 19:02 UTC, arturpimentel requested changes

2020-11-16 19:02 UTC, arturpimentel commented on store/blocks/product/blocks/sideBar.jsonc
> +      "blockClass": "productHeading", // de onde vem o "productHeading"?
```suggestion
      "blockClass": "productHeading",
```

2020-11-16 19:02 UTC, arturpimentel commented on store/blocks/product/blocks/sideBar.jsonc
> +      "blockClass": "productHeading", // de onde vem o "productHeading"?
```suggestion
      "blockClass": "productHeading",
```

2020-11-16 19:02 UTC, arturpimentel commented on styles/css/product/vtex.product-specification-badges.css
> +  border-radius: 8px;
```suggestion
  border-radius: 0.5rem;
```

2020-11-18 15:00 UTC, afonso-praca commented
Sugestões de mudança de texto

Development Effort -> Setup Effort
Does not requires development. -> No development required.

Sugestões de ajustes de comportamento

- Transformar o `compatibility` no menu lateral em um bloco condicional, que não é renderizado quando o valor está vazio.
- Ajustar espaço entre eventual barra de subscription externa e a próxima seção (scressnshots). Deve ser igual (~) ao espaço entre as seções anteriores.

![image](https://user-images.githubusercontent.com/484167/99546776-88fbc780-2995-11eb-8a74-b7be953655ed.png)

2020-11-23 17:14 UTC, arturpimentel approved these changes

2020-11-23 18:29 UTC, pedromtec approved these changes

2020-11-25 15:46 UTC, closed without merging